### ISSUE TITLE
DCGAN Training code

### ISSUE THREAD

**Issue by eldar** [moodoki/semantic_image_inpainting#1]
Hi,

Thanks for sharing your implementation!
Can you please point to the DCGAN training code to use with your model?

Cheers,
Eldar.

**Comment by moodoki** [comment]
Hi,

We reused a model trained previously using code from https://github.com/carpedm20/DCGAN-tensorflow. However that repository was written for tensorflow 0.12, and most probably would not work with tensorflow >= 1.0 without modifications. 

Tensorflow now has GAN models in its contrib, see https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/gan. What we used was the vannila convolutional GAN with 5 conv layers as in carpedm20's code. 

Do remember to change the variable names to match your trained GAN if you are using the newer TFGAN implementation. 

If you need help freezing the checkpoints, I have a gist to do that for you here https://gist.github.com/moodoki/e37a85fb0258b045c005ca3db9cbc7f6
