### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'contrib'

### ISSUE THREAD

**Issue by SreelakshmyJayaram** [moodoki/semantic_image_inpainting#15]
I am running this code in google colab and I got an error like this , 

 File "/content/semantic_image_inpainting/src/model_inpaint.py", line 85, in build_context_loss
    tf.contrib.layers.Flatten(
AttributeError: module 'tensorflow' has no attribute 'contrib'

What am I supposed to do ?

Thanks in advance.

**Comment by moodoki** [comment]
Colab defaults to TensorFlow 2.x which `tf.contrib` is deprecated. You will need to run this in with TensorFlow 1.x. In Colab, you can specify this with 
```
%tensorflow_version 1.x
```

See more in the Colab [documentations](https://colab.research.google.com/notebooks/tensorflow_version.ipynb
).

**Comment by SreelakshmyJayaram** [comment]
Thanks for the response. This works.
