### ISSUE TITLE
why the result is bad?

### ISSUE THREAD

**Issue by micklexqg** [moodoki/semantic_image_inpainting#4]
I tried with the picture:
![image](https://user-images.githubusercontent.com/13776012/34335855-22376b9e-e98d-11e7-80d9-a07ef8265b0f.png)
model file(dcgan-100.pb) is downloaded from the given url.
but the result is too bad:
![image](https://user-images.githubusercontent.com/13776012/34335910-8a99b67e-e98d-11e7-90a0-5e0f90146345.png)

(snapshot several results )
is there any thing wrong?

**Comment by sacherus** [comment]
I've noticed something similar when I was using just one picture. You could try with more pictures and check if you are getting better results

**Comment by sacherus** [comment]
Run with 63 images:
![image](https://user-images.githubusercontent.com/2600737/34732668-3599ebbe-f566-11e7-955a-cce5753ef120.png)
![image](https://user-images.githubusercontent.com/2600737/34732692-44b8523e-f566-11e7-8c55-51f7faf233f3.png)

Run with just 1 image:
![image](https://user-images.githubusercontent.com/2600737/34732734-5b54e6ba-f566-11e7-96d2-d5fd6a5fe335.png)
![image](https://user-images.githubusercontent.com/2600737/34732736-5d6f6466-f566-11e7-8b11-a59a98eb917a.png)

**Comment by piotr-kowenzowski-asi** [comment]
I'm getting similar results... I've noticed that results depend a lot of the image that you used as the input. Sadly to say I'm not able to help.

**Comment by elham1992** [comment]
my program dosen't run carrectly and shows
![errore](https://user-images.githubusercontent.com/36129307/35794293-6c824fb8-0a6a-11e8-8b86-5e4b742d34ce.PNG)

 errors like in the picture below.
what  should I do to solve this problem?

**Comment by piotr-kowenzowski-asi** [comment]
Try:
- python3 if you are using python2
- another version of tensorflow
- debug program with debugger

**Comment by ChengBinJin** [comment]
function create_weighted_mask seems wrong. It is different with the paper. Paper said "a pixel that is very far away from any holes plays very little role in the inpainting process," but it works opposite way.

**Comment by moodoki** [comment]
@ChengBinJin good catch! I noticed that difference recently from our development code. @micklexqg 
 Please use the code in the extensions branch. Bugs should be fixed in that branch, they will be merged into master when time allows :) The branch also contains extension work in our 2018 ICASSP paper.

**Comment by FUHUACANGYUE** [comment]
@moodoki  when i use my own image, I'm getting bad results, and i can not find the code in the extensions branch, where is it?.  And where can i download your  2018 ICASSP paper?
Thanks!

**Comment by FUHUACANGYUE** [comment]
> 
![frontalized_image](https://user-images.githubusercontent.com/42240911/46582205-ed899000-ca75-11e8-89a5-e1cfb3b45bc2.jpg)

**Comment by moodoki** [comment]
https://github.com/moodoki/semantic_image_inpainting/tree/extensions

**Comment by FUHUACANGYUE** [comment]
@moodoki  Thanks for your reply! And i get another problem, please help me to solve it , thanks.
![60cav v0js s0 i zz7xz d](https://user-images.githubusercontent.com/42240911/46590172-dc776800-cae3-11e8-96bb-f98328add1b9.png)
