### ISSUE TITLE
how to get origin graph structure from pb file?

### ISSUE THREAD

**Issue by zhaoying9105** [moodoki/semantic_image_inpainting#5]

**Comment by zhaoying9105** [comment]
Dose the author intentionally concealed the graph structure?

**Comment by moodoki** [comment]
Hi, graph structure is independent of our method. The key insight of our work is that we can use any GAN that was trained beforehand for the task of inpainting. The weights that we linked is a GAN that was trained using old code written by others, we simply reused the weights in this work.
