### ISSUE TITLE
[Feature Request]: WGANs

### ISSUE THREAD

**Issue by JLC7** [moodoki/semantic_image_inpainting#7]
I am interested in implementing this with WGAN / WGAN-GP but am not sure if there would be issues with the perceptual loss term because it relies on the discriminator being able to detect fake or real images. Are there any thoughts on this?

**Comment by moodoki** [comment]
There should be no issue. While we have not tried it, it should be possible for you to train your own GAN using any flavor of loss and use the trained network with our code.
